"""update to schedule model

Revision ID: 5aa28e322dbb
Revises: b3cd035ba858
Create Date: 2023-06-10 13:37:09.146641

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5aa28e322dbb'
down_revision = 'b3cd035ba858'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ticket', 'type',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('ticket', 'price',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('ticket', 'duration',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('train', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('train', 'description',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('train', 'type',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('train', 'capacity',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('train', 'status',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('train', 'status',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('train', 'capacity',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('train', 'type',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('train', 'description',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('train', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('ticket', 'duration',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('ticket', 'price',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('ticket', 'type',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
