"""update to models

Revision ID: 7182d0d095ed
Revises: db7553bfbe78
Create Date: 2023-06-07 15:53:29.856450

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7182d0d095ed'
down_revision = 'db7553bfbe78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('payment_ibfk_1', 'payment', type_='foreignkey')
    op.drop_column('payment', 'payment_gateway')
    op.drop_column('payment', 'currency')
    op.drop_column('payment', 'booking_id')
    op.alter_column('preplanned_trip', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('preplanned_trip', 'description',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('preplanned_trip', 'start_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('preplanned_trip', 'end_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('preplanned_trip', 'starting_destination',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('preplanned_trip', 'final_destination',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('preplanned_trip', 'stops',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('preplanned_trip', 'duration',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('preplanned_trip', 'price',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('preplanned_trip', 'is_active',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('preplanned_trip', 'number_of_seats',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('preplanned_trip', 'booked_seats',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('route', 'departure_time',
               existing_type=mysql.TIME(),
               nullable=True)
    op.alter_column('route', 'arrival_time',
               existing_type=mysql.TIME(),
               nullable=True)
    op.alter_column('route', 'distance',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('route', 'status',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('route', 'type',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('schedule', 'stops',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('schedule', 'departure_time',
               existing_type=mysql.TIME(),
               nullable=True)
    op.alter_column('schedule', 'arrival_time',
               existing_type=mysql.TIME(),
               nullable=True)
    op.alter_column('schedule', 'frequency',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('service', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('service', 'description',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('service', 'price',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('service', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('station', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('station', 'code',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.alter_column('station', 'address',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('station', 'longitude',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('station', 'latitude',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('station', 'is_active',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('ticket', 'type',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('ticket', 'price',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('ticket', 'duration',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('train', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('train', 'description',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('train', 'type',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('train', 'capacity',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('train', 'status',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('train', 'status',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('train', 'capacity',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('train', 'type',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('train', 'description',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('train', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('ticket', 'duration',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('ticket', 'price',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('ticket', 'type',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('station', 'is_active',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('station', 'latitude',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('station', 'longitude',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('station', 'address',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('station', 'code',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('station', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('service', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('service', 'price',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('service', 'description',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('service', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('schedule', 'frequency',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('schedule', 'arrival_time',
               existing_type=mysql.TIME(),
               nullable=False)
    op.alter_column('schedule', 'departure_time',
               existing_type=mysql.TIME(),
               nullable=False)
    op.alter_column('schedule', 'stops',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('route', 'type',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('route', 'status',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('route', 'distance',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('route', 'arrival_time',
               existing_type=mysql.TIME(),
               nullable=False)
    op.alter_column('route', 'departure_time',
               existing_type=mysql.TIME(),
               nullable=False)
    op.alter_column('preplanned_trip', 'booked_seats',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('preplanned_trip', 'number_of_seats',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('preplanned_trip', 'is_active',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('preplanned_trip', 'price',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('preplanned_trip', 'duration',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('preplanned_trip', 'stops',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('preplanned_trip', 'final_destination',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('preplanned_trip', 'starting_destination',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('preplanned_trip', 'end_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('preplanned_trip', 'start_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('preplanned_trip', 'description',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('preplanned_trip', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.add_column('payment', sa.Column('booking_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('payment', sa.Column('currency', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('payment', sa.Column('payment_gateway', mysql.VARCHAR(length=255), nullable=False))
    op.create_foreign_key('payment_ibfk_1', 'payment', 'booking', ['booking_id'], ['id'])
    # ### end Alembic commands ###
