"""empty message

Revision ID: 76dbbe121f3e
Revises: 9f09ace34a14
Create Date: 2023-04-24 12:22:21.982559

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '76dbbe121f3e'
down_revision = '9f09ace34a14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payment', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('payment', 'booking_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.add_column('preplanned_trip', sa.Column('start_date', sa.Date(), nullable=False))
    op.add_column('preplanned_trip', sa.Column('end_date', sa.Date(), nullable=False))
    op.add_column('preplanned_trip', sa.Column('price', sa.Float(), nullable=False))
    op.add_column('preplanned_trip', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.alter_column('preplanned_trip', 'departure_station_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('preplanned_trip', 'arrival_station_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('preplanned_trip', 'train_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('preplanned_trip', 'route_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.add_column('route', sa.Column('departure_time', sa.Time(), nullable=False))
    op.add_column('route', sa.Column('arrival_time', sa.Time(), nullable=False))
    op.alter_column('route', 'starting_station_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('route', 'destination_station_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('route', 'train_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.add_column('schedule', sa.Column('departure_time', sa.Time(), nullable=False))
    op.add_column('schedule', sa.Column('arrival_time', sa.Time(), nullable=False))
    op.alter_column('schedule', 'route_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('schedule', 'train_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('schedule', 'departure_station_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('schedule', 'arrival_station_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('ticket', 'route_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('ticket', 'train_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.add_column('travel_card', sa.Column('start_date', sa.Date(), nullable=False))
    op.add_column('travel_card', sa.Column('end_date', sa.Date(), nullable=False))
    op.add_column('travel_card', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('travel_card', 'is_active')
    op.drop_column('travel_card', 'end_date')
    op.drop_column('travel_card', 'start_date')
    op.alter_column('ticket', 'train_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('ticket', 'route_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('schedule', 'arrival_station_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('schedule', 'departure_station_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('schedule', 'train_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('schedule', 'route_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_column('schedule', 'arrival_time')
    op.drop_column('schedule', 'departure_time')
    op.alter_column('route', 'train_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('route', 'destination_station_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('route', 'starting_station_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_column('route', 'arrival_time')
    op.drop_column('route', 'departure_time')
    op.alter_column('preplanned_trip', 'route_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('preplanned_trip', 'train_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('preplanned_trip', 'arrival_station_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('preplanned_trip', 'departure_station_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_column('preplanned_trip', 'is_active')
    op.drop_column('preplanned_trip', 'price')
    op.drop_column('preplanned_trip', 'end_date')
    op.drop_column('preplanned_trip', 'start_date')
    op.alter_column('payment', 'booking_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('payment', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
