"""empty message

Revision ID: 9f09ace34a14
Revises: 615ff1cd9040
Create Date: 2023-04-24 12:14:32.878330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f09ace34a14'
down_revision = '615ff1cd9040'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('status', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment', 'status')
    # ### end Alembic commands ###
