"""empty message

Revision ID: b18e244fe3cb
Revises: 76dbbe121f3e
Create Date: 2023-04-24 12:27:18.730036

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b18e244fe3cb'
down_revision = '76dbbe121f3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('booking', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('booking', 'train_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('booking', 'route_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.add_column('preplanned_trip', sa.Column('stops', sa.String(length=255), nullable=False))
    op.add_column('schedule', sa.Column('stops', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule', 'stops')
    op.drop_column('preplanned_trip', 'stops')
    op.alter_column('booking', 'route_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('booking', 'train_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('booking', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
