"""status table 2

Revision ID: b3cd035ba858
Revises: db7553bfbe78
Create Date: 2023-06-09 16:01:57.522634

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b3cd035ba858'
down_revision = 'db7553bfbe78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('service', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('service', 'description',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('service', 'price',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('service', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('station', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('station', 'code',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('station', 'address',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('station', 'longitude',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('station', 'latitude',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('station', 'is_active',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('ticket', 'type',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('ticket', 'price',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('ticket', 'duration',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('train', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('train', 'description',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('train', 'type',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('train', 'capacity',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('train', 'status',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('train', 'status',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('train', 'capacity',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('train', 'type',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('train', 'description',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('train', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('ticket', 'duration',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('ticket', 'price',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('ticket', 'type',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('station', 'is_active',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('station', 'latitude',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('station', 'longitude',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('station', 'address',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('station', 'code',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.alter_column('station', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('service', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('service', 'price',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('service', 'description',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('service', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
